apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: portfolio
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    redirectUris:
      - https://portfolio-user3.apps.cluster-enable-e4db.enable-e4db.example.opentlc.com/*
    clientId: portfolio
    secret: changeit
    clientAuthenticatorType: client-secret
    publicClient: true
    directAccessGrantsEnabled: true
